"""
export_dashboard_data.py
--------------------------
Regenerates the dashboard's data file (dashboard/data.js) and chart
images (dashboard/assets/charts/) from the analysis pipeline, so the
HTML/CSS/JS dashboard always reflects the latest numbers without
needing a live Python backend.

"""

import json
import shutil
from pathlib import Path

from data_loading import load_titanic_data
from data_cleaning import clean_titanic_data
from analysis import (
    basic_statistics,
    survival_by_sex,
    survival_by_class,
    survival_by_alone_status,
    survival_by_family_size,
    average_fare_by_class,
)
from visualization import generate_all_charts

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = PROJECT_ROOT / "data" / "Titanic_Sample_Data.xlsx"
CHARTS_DIR = PROJECT_ROOT / "outputs" / "charts"
DASHBOARD_CHARTS_DIR = PROJECT_ROOT / "dashboard" / "assets" / "charts"
DASHBOARD_DATA_JS = PROJECT_ROOT / "dashboard" / "data.js"
RESULTS_JSON = PROJECT_ROOT / "outputs" / "cleaned_data" / "analysis_results.json"
CLEANED_CSV = PROJECT_ROOT / "outputs" / "cleaned_data" / "titanic_cleaned.csv"


def main():
    raw = load_titanic_data(str(DATA_PATH))
    df = clean_titanic_data(raw)

    import visualization
    visualization.OUTPUT_DIR = str(CHARTS_DIR)
    generate_all_charts(df)

    DASHBOARD_CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    for png in CHARTS_DIR.glob("*.png"):
        shutil.copy(png, DASHBOARD_CHARTS_DIR / png.name)

    # Results JSON + cleaned CSV
    results = {
        "basic_statistics": basic_statistics(df),
        "survival_by_sex": survival_by_sex(df).to_dict(),
        "survival_by_class": {str(k): v for k, v in survival_by_class(df).to_dict().items()},
        "survival_by_alone_status": survival_by_alone_status(df).to_dict(),
        "survival_by_family_size": {str(k): v for k, v in survival_by_family_size(df).to_dict().items()},
        "average_fare_by_class": {str(k): v for k, v in average_fare_by_class(df).to_dict().items()},
    }
    RESULTS_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(RESULTS_JSON, "w") as f:
        json.dump(results, f, indent=2)

    df.to_csv(CLEANED_CSV, index=False)

    # Dashboard data.js
    with open(DASHBOARD_DATA_JS, "w") as f:
        f.write("// Auto-generated by src/export_dashboard_data.py\n")
        f.write("// Do not edit by hand -- regenerate from the analysis pipeline.\n")
        f.write("const analysisData = " + json.dumps(results, indent=2) + ";\n")

    print("Dashboard data and charts regenerated successfully.")
    print(f" - {RESULTS_JSON}")
    print(f" - {CLEANED_CSV}")
    print(f" - {DASHBOARD_DATA_JS}")
    print(f" - {DASHBOARD_CHARTS_DIR} ({len(list(DASHBOARD_CHARTS_DIR.glob('*.png')))} charts)")


if __name__ == "__main__":
    main()
